# Generated by Django 4.0.4 on 2022-04-20 19:09

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('bio', models.TextField()),
                ('contact', models.CharField(max_length=300)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('profile', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardsapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_title', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('profile', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardsapp.profile')),
                ('subject', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardsapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Additionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_adds', models.TextField()),
                ('notes', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardsapp.notes')),
                ('profile', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardsapp.profile')),
                ('subject', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcardsapp.subject')),
            ],
        ),
    ]
