# Generated by Django 4.0.4 on 2022-04-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcardsapp', '0002_alter_subject_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilePhoto',
            new_name='profile_pic',
        ),
    ]
